const solc = require("solc");

/**
 * Compiles Solidity source code.
 * @param {string} sourceCode - Raw Solidity source
 * @param {string | undefined} preferredContractName - Optional selected contract name
 * @returns {{ abi, bytecode, contractName, errors, warnings, contracts }}
 */
function compileSolidity(sourceCode, preferredContractName) {
  // Extract pragma version to report it (optional, we always use installed solc)
  const pragmaMatch = sourceCode.match(/pragma solidity\s+([^;]+);/);
  const declaredVersion = pragmaMatch ? pragmaMatch[1].trim() : "unknown";

  // Build solc standard JSON input
  const input = {
    language: "Solidity",
    sources: {
      "Playground.sol": {
        content: sourceCode,
      },
    },
    settings: {
      // Keep generated bytecode compatible with our in-memory Ganache VM.
      evmVersion: "shanghai",
      outputSelection: {
        "*": {
          "*": ["abi", "evm.bytecode"],
        },
      },
      optimizer: {
        enabled: false,
      },
    },
  };

  let output;
  try {
    output = JSON.parse(solc.compile(JSON.stringify(input)));
  } catch (err) {
    return {
      success: false,
      errors: [`Compiler internal error: ${err.message}`],
      warnings: [],
    };
  }

  // Separate errors from warnings
  const errors = [];
  const warnings = [];

  if (output.errors) {
    for (const e of output.errors) {
      if (e.severity === "error") {
        errors.push(e.formattedMessage || e.message);
      } else {
        warnings.push(e.formattedMessage || e.message);
      }
    }
  }

  if (errors.length > 0) {
    return { success: false, errors, warnings };
  }

  const discoveredContracts = [];

  for (const [fileName, fileContracts] of Object.entries(output.contracts || {})) {
    for (const [contractName, contract] of Object.entries(fileContracts || {})) {
      const rawBytecode = contract?.evm?.bytecode?.object || "";
      const hasBytecode = Boolean(rawBytecode);

      discoveredContracts.push({
        fileName,
        contractName,
        abi: contract.abi || [],
        bytecode: hasBytecode ? `0x${rawBytecode}` : null,
        deployable: hasBytecode,
      });
    }
  }

  if (discoveredContracts.length === 0) {
    return {
      success: false,
      errors: ["No contracts found after compilation."],
      warnings,
    };
  }

  let selected = null;

  if (preferredContractName && typeof preferredContractName === "string") {
    selected = discoveredContracts.find((item) => item.contractName === preferredContractName);
    if (!selected) {
      return {
        success: false,
        errors: [
          `Contract \"${preferredContractName}\" not found. Available: ${discoveredContracts
            .map((item) => item.contractName)
            .join(", ")}`,
        ],
        warnings,
        contracts: discoveredContracts.map(({ fileName, contractName, deployable }) => ({
          fileName,
          contractName,
          deployable,
        })),
      };
    }
  }

  if (!selected) {
    selected = discoveredContracts.find((item) => item.deployable) || discoveredContracts[0];
  }

  if (!selected.deployable || !selected.bytecode) {
    return {
      success: false,
      errors: [
        `Selected contract \"${selected.contractName}\" is not deployable. Choose a contract with bytecode.`,
      ],
      warnings,
      contracts: discoveredContracts.map(({ fileName, contractName, deployable }) => ({
        fileName,
        contractName,
        deployable,
      })),
    };
  }

  const abi = selected.abi;
  const bytecode = selected.bytecode;

  return {
    success: true,
    contractName: selected.contractName,
    abi,
    bytecode,
    declaredVersion,
    warnings,
    contracts: discoveredContracts.map(({ fileName, contractName, deployable }) => ({
      fileName,
      contractName,
      deployable,
    })),
  };
}

module.exports = { compileSolidity };
